//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace problema3.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaccion_bancaria
    {
        public int id_transaccion_bancaria { get; set; }
        public string monto { get; set; }
        public int origen { get; set; }
        public int destino { get; set; }
    
        public virtual cuenta_bancaria cuenta_bancaria { get; set; }
        public virtual cuenta_bancaria cuenta_bancaria1 { get; set; }
    }
}
