//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace problema9v1.ApiPersona {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApiPersona.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        problema9v1.ApiPersona.HelloWorldResponse HelloWorld(problema9v1.ApiPersona.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<problema9v1.ApiPersona.HelloWorldResponse> HelloWorldAsync(problema9v1.ApiPersona.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarPersona", ReplyAction="*")]
        problema9v1.ApiPersona.insertarPersonaResponse insertarPersona(problema9v1.ApiPersona.insertarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<problema9v1.ApiPersona.insertarPersonaResponse> insertarPersonaAsync(problema9v1.ApiPersona.insertarPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id_persona del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPersona", ReplyAction="*")]
        problema9v1.ApiPersona.eliminarPersonaResponse eliminarPersona(problema9v1.ApiPersona.eliminarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<problema9v1.ApiPersona.eliminarPersonaResponse> eliminarPersonaAsync(problema9v1.ApiPersona.eliminarPersonaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarPersona", ReplyAction="*")]
        problema9v1.ApiPersona.modificarPersonaResponse modificarPersona(problema9v1.ApiPersona.modificarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<problema9v1.ApiPersona.modificarPersonaResponse> modificarPersonaAsync(problema9v1.ApiPersona.modificarPersonaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public problema9v1.ApiPersona.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(problema9v1.ApiPersona.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public problema9v1.ApiPersona.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(problema9v1.ApiPersona.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarPersona", Namespace="http://tempuri.org/", Order=0)]
        public problema9v1.ApiPersona.insertarPersonaRequestBody Body;
        
        public insertarPersonaRequest() {
        }
        
        public insertarPersonaRequest(problema9v1.ApiPersona.insertarPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ci;
        
        public insertarPersonaRequestBody() {
        }
        
        public insertarPersonaRequestBody(string nombre, string apellido, string ci) {
            this.nombre = nombre;
            this.apellido = apellido;
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public problema9v1.ApiPersona.insertarPersonaResponseBody Body;
        
        public insertarPersonaResponse() {
        }
        
        public insertarPersonaResponse(problema9v1.ApiPersona.insertarPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int insertarPersonaResult;
        
        public insertarPersonaResponseBody() {
        }
        
        public insertarPersonaResponseBody(int insertarPersonaResult) {
            this.insertarPersonaResult = insertarPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarPersona", Namespace="http://tempuri.org/", Order=0)]
        public problema9v1.ApiPersona.eliminarPersonaRequestBody Body;
        
        public eliminarPersonaRequest() {
        }
        
        public eliminarPersonaRequest(problema9v1.ApiPersona.eliminarPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id_persona;
        
        public eliminarPersonaRequestBody() {
        }
        
        public eliminarPersonaRequestBody(string id_persona) {
            this.id_persona = id_persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public problema9v1.ApiPersona.eliminarPersonaResponseBody Body;
        
        public eliminarPersonaResponse() {
        }
        
        public eliminarPersonaResponse(problema9v1.ApiPersona.eliminarPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int eliminarPersonaResult;
        
        public eliminarPersonaResponseBody() {
        }
        
        public eliminarPersonaResponseBody(int eliminarPersonaResult) {
            this.eliminarPersonaResult = eliminarPersonaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarPersona", Namespace="http://tempuri.org/", Order=0)]
        public problema9v1.ApiPersona.modificarPersonaRequestBody Body;
        
        public modificarPersonaRequest() {
        }
        
        public modificarPersonaRequest(problema9v1.ApiPersona.modificarPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string id_persona;
        
        public modificarPersonaRequestBody() {
        }
        
        public modificarPersonaRequestBody(string nombre, string apellido, string ci, string id_persona) {
            this.nombre = nombre;
            this.apellido = apellido;
            this.ci = ci;
            this.id_persona = id_persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public problema9v1.ApiPersona.modificarPersonaResponseBody Body;
        
        public modificarPersonaResponse() {
        }
        
        public modificarPersonaResponse(problema9v1.ApiPersona.modificarPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int modificarPersonaResult;
        
        public modificarPersonaResponseBody() {
        }
        
        public modificarPersonaResponseBody(int modificarPersonaResult) {
            this.modificarPersonaResult = modificarPersonaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : problema9v1.ApiPersona.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<problema9v1.ApiPersona.WebServiceSoap>, problema9v1.ApiPersona.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        problema9v1.ApiPersona.HelloWorldResponse problema9v1.ApiPersona.WebServiceSoap.HelloWorld(problema9v1.ApiPersona.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            problema9v1.ApiPersona.HelloWorldRequest inValue = new problema9v1.ApiPersona.HelloWorldRequest();
            inValue.Body = new problema9v1.ApiPersona.HelloWorldRequestBody();
            problema9v1.ApiPersona.HelloWorldResponse retVal = ((problema9v1.ApiPersona.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<problema9v1.ApiPersona.HelloWorldResponse> problema9v1.ApiPersona.WebServiceSoap.HelloWorldAsync(problema9v1.ApiPersona.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<problema9v1.ApiPersona.HelloWorldResponse> HelloWorldAsync() {
            problema9v1.ApiPersona.HelloWorldRequest inValue = new problema9v1.ApiPersona.HelloWorldRequest();
            inValue.Body = new problema9v1.ApiPersona.HelloWorldRequestBody();
            return ((problema9v1.ApiPersona.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        problema9v1.ApiPersona.insertarPersonaResponse problema9v1.ApiPersona.WebServiceSoap.insertarPersona(problema9v1.ApiPersona.insertarPersonaRequest request) {
            return base.Channel.insertarPersona(request);
        }
        
        public int insertarPersona(string nombre, string apellido, string ci) {
            problema9v1.ApiPersona.insertarPersonaRequest inValue = new problema9v1.ApiPersona.insertarPersonaRequest();
            inValue.Body = new problema9v1.ApiPersona.insertarPersonaRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.ci = ci;
            problema9v1.ApiPersona.insertarPersonaResponse retVal = ((problema9v1.ApiPersona.WebServiceSoap)(this)).insertarPersona(inValue);
            return retVal.Body.insertarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<problema9v1.ApiPersona.insertarPersonaResponse> problema9v1.ApiPersona.WebServiceSoap.insertarPersonaAsync(problema9v1.ApiPersona.insertarPersonaRequest request) {
            return base.Channel.insertarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<problema9v1.ApiPersona.insertarPersonaResponse> insertarPersonaAsync(string nombre, string apellido, string ci) {
            problema9v1.ApiPersona.insertarPersonaRequest inValue = new problema9v1.ApiPersona.insertarPersonaRequest();
            inValue.Body = new problema9v1.ApiPersona.insertarPersonaRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.ci = ci;
            return ((problema9v1.ApiPersona.WebServiceSoap)(this)).insertarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        problema9v1.ApiPersona.eliminarPersonaResponse problema9v1.ApiPersona.WebServiceSoap.eliminarPersona(problema9v1.ApiPersona.eliminarPersonaRequest request) {
            return base.Channel.eliminarPersona(request);
        }
        
        public int eliminarPersona(string id_persona) {
            problema9v1.ApiPersona.eliminarPersonaRequest inValue = new problema9v1.ApiPersona.eliminarPersonaRequest();
            inValue.Body = new problema9v1.ApiPersona.eliminarPersonaRequestBody();
            inValue.Body.id_persona = id_persona;
            problema9v1.ApiPersona.eliminarPersonaResponse retVal = ((problema9v1.ApiPersona.WebServiceSoap)(this)).eliminarPersona(inValue);
            return retVal.Body.eliminarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<problema9v1.ApiPersona.eliminarPersonaResponse> problema9v1.ApiPersona.WebServiceSoap.eliminarPersonaAsync(problema9v1.ApiPersona.eliminarPersonaRequest request) {
            return base.Channel.eliminarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<problema9v1.ApiPersona.eliminarPersonaResponse> eliminarPersonaAsync(string id_persona) {
            problema9v1.ApiPersona.eliminarPersonaRequest inValue = new problema9v1.ApiPersona.eliminarPersonaRequest();
            inValue.Body = new problema9v1.ApiPersona.eliminarPersonaRequestBody();
            inValue.Body.id_persona = id_persona;
            return ((problema9v1.ApiPersona.WebServiceSoap)(this)).eliminarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        problema9v1.ApiPersona.modificarPersonaResponse problema9v1.ApiPersona.WebServiceSoap.modificarPersona(problema9v1.ApiPersona.modificarPersonaRequest request) {
            return base.Channel.modificarPersona(request);
        }
        
        public int modificarPersona(string nombre, string apellido, string ci, string id_persona) {
            problema9v1.ApiPersona.modificarPersonaRequest inValue = new problema9v1.ApiPersona.modificarPersonaRequest();
            inValue.Body = new problema9v1.ApiPersona.modificarPersonaRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.ci = ci;
            inValue.Body.id_persona = id_persona;
            problema9v1.ApiPersona.modificarPersonaResponse retVal = ((problema9v1.ApiPersona.WebServiceSoap)(this)).modificarPersona(inValue);
            return retVal.Body.modificarPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<problema9v1.ApiPersona.modificarPersonaResponse> problema9v1.ApiPersona.WebServiceSoap.modificarPersonaAsync(problema9v1.ApiPersona.modificarPersonaRequest request) {
            return base.Channel.modificarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<problema9v1.ApiPersona.modificarPersonaResponse> modificarPersonaAsync(string nombre, string apellido, string ci, string id_persona) {
            problema9v1.ApiPersona.modificarPersonaRequest inValue = new problema9v1.ApiPersona.modificarPersonaRequest();
            inValue.Body = new problema9v1.ApiPersona.modificarPersonaRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.ci = ci;
            inValue.Body.id_persona = id_persona;
            return ((problema9v1.ApiPersona.WebServiceSoap)(this)).modificarPersonaAsync(inValue);
        }
    }
}
